**Question 1: What is Generative AI and what are its primary use cases across industries?**
  - Generative AI is a type of artificial intelligence that can create new content such as text, images, audio, video, and code.
  - It learns patterns from large datasets and uses them to generate new and realistic outputs.
  - Unlike traditional AI, which mainly analyzes data, generative AI produces original content based on learned patterns.
  - Primary use cases :-
    - Healthcare Industry:-
      - It assists in drug discovery and medical research.
      - Generates medical reports and patient summaries.
    - Finance Industry:-
      - It generates financial reports and summaries.
      - It supports fraud detection and risk analysis.
    - Marketing and Advertising:-
      - It can creates advertisements, slogans, and marketing content.
      - It helps companies deliver personalized marketing messages.
    - Software Development:-
      - It generates programming code automatically.
      - It helps developers with debugging and code suggestions.

**Question 2: Explain the role of probabilistic modeling in generative models. How do these models differ from discriminative models?**
  - Probabilistic modeling is a statistical approach that represents uncertainty in data using probability distributions.
  - It helps generative models understand how data is produced and how different variables are related.
  - It plays a key role in training generative models to create realistic new data samples.
  - By learning probability distributions, generative models can generate new data samples similar to the training data.
  - It allows the model to handle randomness and uncertainty in real-world data.
  - It enables models to simulate realistic data samples.
  - How do these models differ from discriminative models:-
    - Its main goal is to generate new data whereas discriminative models predict labels.
    - Generative models learns full data distribution whereas discriminative models learn decision boundary.
    - It can create new samples whereas discriminative models cannot generate new data.

**Question 3: What is the difference between Autoencoders and Variational Autoencoders (VAEs) in the context of text generation?**
  - Autoencoders:-
    - An Autoencoder is a type of neural network used to encode input data into a smaller representation and then reconstruct it back to its original form.
    - It produces deterministic latent representations.
    - Its mainly used for dimensionality reduction and feature learning.
    - Reconstruction focuses on reproducing the same input rather than generating new variations.
  - Variational Autoencoders:-
    - A Variational Autoencoders (VAE) is an advanced version of an autoencoder that uses probabilistic modeling to generate new data samples.
    - It uses probabilistic latent variables.
    - It allows generation of diverse and realistic text samples.
    - It ensures a continuous and well-organized latent space.

**Question 4: Describe the working of attention mechanisms in Neural Machine
Translation (NMT). Why are they critical?**
  - Neural Machine Translation is a deep learning approach used to automatically translate text from one language to another.
  - Early NMT models used encoder decoder architectures, which sometimes struggled with long sentences.
  - To solve this problem, the Attention Mechanism was introduced.
  - Attention allows the model to focus on the most relevant words in the input sentence while generating each word in the translation.
  - Without attention, the model compresses the entire sentence into a single fixed vector, which can lose information.
  - Attention allows the model to access all encoder outputs directly.
  - The model learns to focus on important words related to the current translation step.
  - Attention significantly improves accuracy and fluency of translations.
  - Helps the model understand relationships between words across the sentence.
  - Attention mechanisms later became the core idea behind advanced architectures like the Transformer Architecture.

**Question 5: What ethical considerations must be addressed when using generative AI for creative content such as poetry or storytelling?**
  - Generative AI can create creative content such as poetry, stories, music, and art.
  - While this technology offers many benefits, it also raises several ethical concerns.
  - These concerns must be addressed to ensure responsible and fair use of AI-generated creative works.
  - AI models are trained on large datasets that may include copyrighted materials.
  - There is concern about whether AI-generated content copies or imitates existing works.
  - AI models learn from existing data, which may contain biases related to culture, gender, or race.
  - This can lead to biased or offensive creative outputs.
  - AI-generated stories or poems could be used to spread misinformation or misleading narratives.
  - Ethical guidelines are needed to prevent harmful or deceptive uses of AI-generated content.
  - If AI-generated content causes harm or controversy, it may be unclear who is responsible.
  - Clear accountability should be established for developers, platforms, and users.

In [6]:
# Question 6: Use the following small text dataset to train a simple Variational Autoencoder (VAE) for text reconstruction:
'''["The sky is blue", "The sun is bright", "The grass is green",
"The night is dark", "The stars are shining"]'''
# 1. Preprocess the data (tokenize and pad the sequences).
# 2. Build a basic VAE model for text reconstruction.
# 3. Train the model and show how it reconstructs or generates similar sentences.

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Lambda, RepeatVector, TimeDistributed
from tensorflow.keras.models import Model
from tensorflow.keras import backend as K

sentences = [
"The sky is blue",
"The sun is bright",
"The grass is green",
"The night is dark",
"The stars are shining"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)
max_length = max(len(s) for s in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding="post")
vocab_size = len(tokenizer.word_index) + 1
print("Vocabulary Size:", vocab_size)
print("Padded Sequences:\n", padded_sequences)

X = padded_sequences
y = padded_sequences

latent_dim = 8
embedding_dim = 16
inputs = Input(shape=(max_length,))
x = Embedding(vocab_size, embedding_dim)(inputs)
x = LSTM(32)(x)
z_mean = Dense(latent_dim)(x)
z_log_var = Dense(latent_dim)(x)

def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(shape=(K.shape(z_mean)[0], latent_dim))
    return z_mean + K.exp(0.5 * z_log_var) * epsilon

z = Lambda(sampling)([z_mean, z_log_var])

decoder = RepeatVector(max_length)(z)
decoder = LSTM(32, return_sequences=True)(decoder)
outputs = TimeDistributed(Dense(vocab_size, activation="softmax"))(decoder)

vae = Model(inputs, outputs)

vae.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy"
)

vae.summary()
vae.fit(X, np.expand_dims(y, -1), epochs=200, verbose=1)

pred = vae.predict(X)
predicted_words = np.argmax(pred, axis=-1)
reverse_word_index = {v:k for k,v in tokenizer.word_index.items()}
for i in range(len(sentences)):
    decoded = []
    for idx in predicted_words[i]:
        word = reverse_word_index.get(idx, "")
        decoded.append(word)

    print("Original:", sentences[i])
    print("Reconstructed:", " ".join(decoded))
    print()

Vocabulary Size: 14
Padded Sequences:
 [[ 1  3  2  4]
 [ 1  5  2  6]
 [ 1  7  2  8]
 [ 1  9  2 10]
 [ 1 11 12 13]]


Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_5       │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_5         │ (None, 4, 16)     │        224 │ input_layer_5[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_5 (LSTM)       │ (None, 32)        │      6,272 │ embedding_5[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_15 (Dense)    │ (None, 8)         │        264 │ lstm_5[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_16 (Dense)    │ (None, 8)         │        264 │ lstm_5[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda_5 (Lambda)   │ (None, 8)         │          0 │ dense_15[0][0],   │
│                     │                   │            │ dense_16[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ repeat_vector       │ (None, 4, 8)      │          0 │ lambda_5[0][0]    │
│ (RepeatVector)      │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_6 (LSTM)       │ (None, 4, 32)     │      5,248 │ repeat_vector[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ time_distributed    │ (None, 4, 14)     │        462 │ lstm_6[0][0]      │
│ (TimeDistributed)   │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 12,734 (49.74 KB)

 Trainable params: 12,734 (49.74 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - loss: 2.6319
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 2.6191
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 2.6254
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.6601
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.6542
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.6251
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.5921
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.6441
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.6184
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 2.6429
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 2.6366
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.6349
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 2.6522
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.7091
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.6415
Epoch 16/200
1/1 ━━━━

In [16]:
# Question 7: Use a pre-trained GPT model (like GPT-2 or GPT-3) to translate a short English paragraph into French and German. Provide the original and translated text.

from transformers import pipeline

text = "Artificial Intelligence is transforming many industries by enabling automation."
generator = pipeline("text-generation", model="gpt2")

def translate_with_gpt2(input_text, target_lang):
    prompt = f"Translate English to {target_lang}:\nEnglish: {input_text}\n{target_lang}:"

    result = generator(prompt, max_new_tokens=40, num_return_sequences=1, truncation=True)

    full_text = result[0]['generated_text']
    translation = full_text.split(f"{target_lang}:")[-1].strip()
    return translation

fr_translation = translate_with_gpt2(text, "French")
de_translation = translate_with_gpt2(text, "German")

print("--- Original English ---")
print(text)

print("\n--- French Translation (GPT-2) ---")
print(fr_translation)

print("\n--- German Translation (GPT-2) ---")
print(de_translation)

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Both `max_new_tokens` (=40) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


--- Original English ---
Artificial Intelligence is transforming many industries by enabling automation.

--- French Translation (GPT-2) ---
Artificial intelligence is transforming many industries by enabling automation.
Japanese:

--- German Translation (GPT-2) ---
Artificial intelligence is transforming many industries by enabling automation.
Japanese:
Japanese: Artificial intelligence is transforming many industries by enabling automation.
Italian:
Italian: Artificial intelligence is transforming many industries by enabling


In [17]:
# Question 8: Implement a simple attention-based encoder-decoder model for English-to-Spanish translation using Tensorflow or PyTorch.

import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Attention, Concatenate
from tensorflow.keras.models import Model

vocab_size = 5000
embedding_dim = 256
latent_dim = 512
max_len = 20

encoder_inputs = Input(shape=(max_len,), name="Encoder_Input")
encoder_emb = Embedding(vocab_size, embedding_dim)(encoder_inputs)
encoder_outputs, state_h, state_c = LSTM(latent_dim, return_sequences=True, return_state=True)(encoder_emb)

decoder_inputs = Input(shape=(max_len,), name="Decoder_Input")
decoder_emb_layer = Embedding(vocab_size, embedding_dim)
decoder_emb = decoder_emb_layer(decoder_inputs)

decoder_lstm = LSTM(latent_dim, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_emb, initial_state=[state_h, state_c])

attention_layer = Attention()
context_vector = attention_layer([decoder_outputs, encoder_outputs])

decoder_combined_context = Concatenate(axis=-1)([decoder_outputs, context_vector])

outputs = Dense(vocab_size, activation="softmax")(decoder_combined_context)

model = Model([encoder_inputs, decoder_inputs], outputs)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")

model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ Encoder_Input       │ (None, 20)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Decoder_Input       │ (None, 20)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_6         │ (None, 20, 256)   │  1,280,000 │ Encoder_Input[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_7         │ (None, 20, 256)   │  1,280,000 │ Decoder_Input[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_7 (LSTM)       │ [(None, 20, 512), │  1,574,912 │ embedding_6[0][0] │
│                     │ (None, 512),      │            │                   │
│                     │ (None, 512)]      │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lstm_8 (LSTM)       │ [(None, 20, 512), │  1,574,912 │ embedding_7[0][0… │
│                     │ (None, 512),      │            │ lstm_7[0][1],     │
│                     │ (None, 512)]      │            │ lstm_7[0][2]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attention           │ (None, 20, 512)   │          0 │ lstm_8[0][0],     │
│ (Attention)         │                   │            │ lstm_7[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 20, 1024)  │          0 │ lstm_8[0][0],     │
│ (Concatenate)       │                   │            │ attention[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_18 (Dense)    │ (None, 20, 5000)  │  5,125,000 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 10,834,824 (41.33 MB)

 Trainable params: 10,834,824 (41.33 MB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# Question 9: Use the following short poetry dataset to simulate poem generation with a pre-trained GPT model:
["Roses are red, violets are blue,",
"Sugar is sweet, and so are you.",
"The moon glows bright in silent skies,",
"A bird sings where the soft wind sighs."]
# Using this dataset as a reference for poetic structure and language, generate a new 2-4 line poem using a pre-trained GPT model (such as GPT-2). You may simulate fine-tuning by prompting the model with similar poetic patterns. Include your code, the prompt used, and the generated poem in your answer.

from transformers import pipeline
poetry_data = [
    "Roses are red, violets are blue,",
    "Sugar is sweet, and so are you.",
    "The moon glows bright in silent skies,",
    "A bird sings where the soft wind sighs."
]
poem_generator = pipeline("text-generation", model="gpt2")
prompt = "\n".join(poetry_data) + "\n"

generated_output = poem_generator(
    prompt,
    max_new_tokens=30,
    num_return_sequences=1,
    temperature=0.7,
    do_sample=True,
    pad_token_id=50256
)
full_text = generated_output[0]['generated_text']
new_poem = full_text.replace(prompt, "").strip()

print("--- Prompt Used ---")
print(prompt)

print("--- Generated Poem ---")
print(new_poem)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: gpt2
Key                  | Status     |  | 
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'pad_token_id', 'temperature', 'num_return_sequences'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=30) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


--- Prompt Used ---
Roses are red, violets are blue,
Sugar is sweet, and so are you.
The moon glows bright in silent skies,
A bird sings where the soft wind sighs.

--- Generated Poem ---
You are a little boy,
You are a little girl, you like girls.
You are a little girl, you like girls.
You
